### ISSUE TITLE
Error making network request through the SDK in Android API level <= 4.4.4

### ISSUE THREAD

**Issue by gsanguinetti** [Ingenico-ePayments/connect-sdk-client-android#3]
Hi,
I'm getting an error every time I'm trying to get the IIn details for a payment (session.getIinDetails()) in Android API level lower than 20: 

"com.globalcollect.gateway.sdk.client.android.sdk.exception.CommunicationException: IOException while opening connection Connection closed by peer, javax.net.ssl.SSLException: Connection closed by peer"

We were doing a little research about the error and found this: https://stackoverflow.com/questions/37006416/sslexception-connection-closed-by-peer-on-android-4-x-versions

**Comment by rikvanthof** [comment]
30 June 2018 is the deadline for disabling SSL/early TLS and implementing a more secure encryption protocol – TLS 1.1 or higher (TLS v1.2 is strongly encouraged) in order to meet the PCI Data Security Standard (PCI DSS) for safeguarding payment data. This means we don't support TLS 1.0 connections anymore on our platform. Please see this blog post from the PCI Security Standards Council: https://blog.pcisecuritystandards.org/are-you-ready-for-30-june-2018-sayin-goodbye-to-ssl-early-tls
