### ISSUE TITLE
Where can we find a ApiKey or SecretKey?

### ISSUE THREAD

**Issue by SjoerdPerfors** [Ingenico-ePayments/connect-sdk-client-android#7]
Following the documentation we need this info:

```
connect.api.apiKeyId for the API key id to use. This can be retrieved from the Configuration Center.
connect.api.secretApiKey for the secret API key to use. This can be retrieved from the Configuration Center.
connect.api.merchantId for your merchant ID.
```

This form gives an error: https://epayments.developer-ingenico.com/signup-for-sandbox/ after filling in your details.

We've created a account for: https://secure.ogone.com/Ncol/Test/BackOffice/Login
But If we log into this website we cannot find these keys or a way how to create these. I've tried mailing Ingenico but without any luck.

**Comment by IngenicoEPayments** [comment]
We are aware of the issue with the sign-up forms and are working to resolve that. Apologies for the fact that it isn't working at the moment. 

I'm afraid that the only way to get the credentials you need are to contact Ogone support. I will make sure that they are aware of your need.

**Comment by SjoerdPerfors** [comment]
Actually I already have 3 mail threads about this with Ingenico support team. It seems it's very hard to get in touch with someone who has any knowledge about this SDK or this subject.

If you can get me in touch with someone who can help us, please do so. Thanks!

**Comment by rikvanthof** [comment]
Do you have support ticket IDs for me? I'll make sure you are contacted by somebody who can help you.

**Comment by ronaldmiddelkoop** [comment]
Hi Sjoerd, the issue with the sandbox signup should now be fixed, you should be able to get your API credentials that way. Apologies again for the inconvenience!

**Comment by SjoerdPerfors** [comment]
Thanks you!

**Comment by worldline-direct-support-team** [comment]
Hi @cb-alfredjoseph, it looks like you're commenting on a closed ticket, on the wrong repository. It seems you're integrating with Direct, not with Connect. The SDKs for Direct can be found at [https://github.com/wl-online-payments-direct].

Your question also seems better suited for general support instead of SDK support.
You can contact Direct support at [https://support.direct.ingenico.com/help/contact/].

More information about the authentication in general and the API key specifically can be found at [https://support.direct.ingenico.com/documentation/api/authentication]. Please note that the API secret is only shown once.
